---
all:
  children:
    ubuntu_servers:
      hosts:
        ubuntu-tf-01:
          ansible_host: 192.168.178.101
        gitea-01:
          ansible_host: 192.168.178.104
        jenkins-01:
          ansible_host: 192.168.178.105

      vars:
        ansible_user: moustafa

    gitea_servers:
      hosts:
        gitea-01:

    jenkins_servers:
      hosts:
        jenkins-01:
