---
all:
  vars:
    ansible_user: moustafa

  children:
    ubuntu_servers:
      hosts:
        ubuntu-tf-01:
          ansible_host: 192.168.178.103

        gitea-01:
          ansible_host: 192.168.178.104

        jenkins-01:
          ansible_host: 192.168.178.105

        mgmt-01:
          ansible_host: 192.168.178.106

    gitea_servers:
      hosts:
        gitea-01:
          ansible_host: 192.168.178.104

    jenkins_servers:
      hosts:
        jenkins-01:
          ansible_host: 192.168.178.105

    mgmt_servers:
      hosts:
        mgmt-01:
          ansible_host: 192.168.178.106

k8s_control_plane:
  hosts:
    k8s-cp-01:
      ansible_host: 192.168.178.110

k8s_workers:
  hosts:
    k8s-worker-01:
      ansible_host: 192.168.178.111

k8s_cluster:
  children:
    k8s_control_plane:
    k8s_workers:
