---
rke2_agent_channel: stable

rke2_agent_config_dir: /etc/rancher/rke2
rke2_agent_node_ip: "{{ ansible_host }}"

rke2_agent_server_url: "https://{{ hostvars[groups['k8s_control_plane'][0]].ansible_host }}:9345"
